# District Snow Day Settings

# Snow Day Status
snow_days:
  allotted: 6
  used: 1

# Community Context
community:
  state: "Michigan"
  county: "Kent"
  city: "Rockford"
  type: "rural"  # urban, suburban, rural
  winter_experience: "experienced"  # experienced, moderate, inexperienced
  geographic_area: {
    latitude: 43.1206,
    longitude: -85.5561,
    elevation_ft: 728
  }

# Current Conditions
current:
  hype_level: 3  # Scale of 1-10
  nearby_closures: 0  # Number of nearby districts closed
  social_media_buzz: "medium"  # high, medium, low

# Additional Notes
notes:
  - "It is important to remember that school starts at 7:40 AM - so factor this in when making decisions."
  - "You should also factor in that snow crews could be out before 7:40 AM clearing roads, so think of that when seeing snowfall earlier in the night/morning."
  - "Since we live in Michigan, our community is used to snow and winter weather - factor this in when making decisions, it usually takes a lot to close schools"
  - "You should be conservative when calling snow days and giving your percetange chance, they are not just given out like candy to satisfy everyone."
  - "Weather alerts must be specifically relevant to Kent County and Rockford area to be considered in probability calculations."
  - "If the weather is not expected to be a significant factor in the decision, you should not call a snow day."
  - "It is very important for you to remember that you are competing against humans to predict the most accurate snow day probability - try to be as accurate as possible with your percentage."