name: Deploy Static Site

on:
  schedule:
    - cron: '36 0 * * 0-4'  # Runs at 7:36PM EST (00:36 UTC) Sunday through Thursday
    # Update to '30 23 * * 0-4' during DST to run at 7:30PM EDT (23:30 UTC)
  workflow_dispatch:  # Allows manual triggering
    inputs:
      skip_generation:
        description: 'Skip running main.py'
        required: false
        type: boolean
        default: false

permissions:
  contents: write  # Changed to write to allow committing
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
      
      - name: Set up Python
        if: ${{ !inputs.skip_generation }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        if: ${{ !inputs.skip_generation }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run site generator
        if: ${{ !inputs.skip_generation }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          ZIP_CODE: ${{ secrets.ZIP_CODE }}
          MODEL_NAME: ${{ vars.DEFAULT_MODEL }}
          WEATHER_MODEL: ${{ vars.WEATHER_MODEL }}
          BLIZZARD_MODEL: ${{ vars.BLIZZARD_MODEL }}
          ASSISTANT_MODEL: ${{ vars.ASSISTANT_MODEL }}
          SELECTION_MODEL: ${{ vars.SELECTION_MODEL }}
          TERMINATION_MODEL: ${{ vars.TERMINATION_MODEL }}
          BLIZZARD_ENV: 'production'
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add static/history.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update history.json" && git push)

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './static'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2