name: Update History

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Needed to commit changes

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Commit and push history
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add static/history.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update history.json" && git push)